/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 * this is a String encryption program that was generated by ChatGPT
 *
 * @author Zahin
 */

import java.util.Scanner;

public class EncryptionProgram {
    public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    System.out.print("Enter message to be encrypted: ");
    String message = sc.nextLine();

    String encryptedMessage = encrypt(message);
    System.out.println("Encrypted message: " + encryptedMessage);
  }

  public static String encrypt(String message) {
    // Step 1: Shift each letter 3 positions to the right
    StringBuilder shiftedMessage = new StringBuilder();
    for (int i = 0; i < message.length(); i++) {
      char c = message.charAt(i);
      if (Character.isLetter(c)) {
        char shiftedChar = (char) (c + 3);
        shiftedMessage.append(shiftedChar);
      } else {
        shiftedMessage.append(c);
      }
    }

    // Step 2: Reverse the message and shift the second half of each line one position to the left
    StringBuilder encryptedMessage = new StringBuilder();
    String reversedMessage = shiftedMessage.reverse().toString();
    int mid = reversedMessage.length() / 2;
    for (int i = 0; i < reversedMessage.length(); i++) {
      char c = reversedMessage.charAt(i);
      if (i >= mid) {
        c = (char) (c - 1);
      }
      encryptedMessage.append(c);
    }

    return encryptedMessage.toString();
  }
}
